services:
  app:
    build:
      context: ../ # Change context to the parent directory (portal.itsupport.com.bd/)
      dockerfile: docker-ampnm/Dockerfile # Specify Dockerfile path relative to new context
    volumes:
      - ../:/var/www/html/ # Mount the parent directory (portal.itsupport.com.bd/) as the web root
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=127.0.0.1
      - DB_NAME=network_monitor
      - DB_USER=user
      - DB_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
      - ADMIN_PASSWORD=password
      - LICENSE_API_URL=https://portal.itsupport.com.bd/verify_license.php
      - APP_LICENSE_KEY=
    restart: unless-stopped
    network_mode: "host"

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: network_monitor
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data: